services:
  app_proxy:
    environment:
      APP_HOST: whisparr-v3
      APP_PORT: 6970
      PROXY_AUTH_WHITELIST: /api/*
    container_name: whisparr-v3_app_proxy_1
    restart: unless-stopped

  whisparr-v3:
    image: ghcr.io/hotio/whisparr:v3
    container_name: whisparr-v3
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Sao_Paulo
      - WEBUI_PORTS=6970/tcp
      - WHISPARR__SERVER__PORT=6970
      - WHISPARR__APP__INSTANCENAME=Whisparr v3
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
    restart: unless-stopped

  mac:
    image: >-
      getumbrel/media-app-configurator:v1.3.0@sha256:67e75dd9f5a14402b7816119a8e20189bc2465484cea077909d164687e59742b
    user: '1000:1000'
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
    environment:
      APP_ID: salesawagner-whisparr-v3
      APP_URL: http://whisparr-v3:6970
    container_name: salesawagner-whisparr-v3_mac_1
