services:
  app_proxy:
    environment:
      APP_HOST: stash
      APP_PORT: 9999
      PROXY_AUTH_WHITELIST: /api/*
    container_name: stash_app_proxy_1
    restart: unless-stopped

  server:
    image: ghcr.io/hotio/stash
    container_name: stash
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Sao_Paulo
      - WEBUI_PORTS=9999/tcp
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
    restart: unless-stopped

  mac:
    image: >-
      getumbrel/media-app-configurator:v1.3.0@sha256:67e75dd9f5a14402b7816119a8e20189bc2465484cea077909d164687e59742b
    user: '1000:1000'
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
    environment:
      APP_ID: salesawagner-stash
      APP_URL: http://stash:9999
    container_name: salesawagner-stash_mac_1
