services:
  app_proxy:
    environment:
      APP_HOST: clonarr
      APP_PORT: 6060
      PROXY_AUTH_WHITELIST: /api/*
    container_name: clonarr_app_proxy_1
    restart: unless-stopped

  clonarr:
    image: ghcr.io/prophetse7en/clonarr:latest
    container_name: clonarr
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Sao_Paulo
      - WEBUI_PORTS=7777/tcp
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
    restart: unless-stopped

  mac:
    image: getumbrel/media-app-configurator:v1.3.2@sha256:9ff34bda1e36ffe5a028d2463f4aaa9f20b93e8bec4392da077137c56bea3c34
    user: '1000:1000'
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
    environment:
      APP_ID: salesawagner-clonarr
      APP_URL: http://clonarr:7777
      RADARR_URL: http://radarr:7878
      RADARR_CONFIG_XML: ${APP_PROWLARR_RADARR_CONFIG_XML}
      SONARR_URL: http://sonarr:8989
      SONARR_CONFIG_XML: ${APP_PROWLARR_SONARR_CONFIG_XML}
    container_name: salesawagner-clonarr_mac_1
